const express = require('express');
const router = express.Router();
const auth = require('../middlewares/auth');
const noteController = require('../controllers/noteController');
const { createNoteValidation, updateNoteValidation } = require('../validations/noteValidation');
const validate = require('../middlewares/validate');
router.use(auth);
router.post('/',createNoteValidation, validate, noteController.createNote);
router.get('/', noteController.getNotes);
router.get('/:id', noteController.getNote);
router.put('/:id',updateNoteValidation, validate, noteController.updateNote);
router.delete('/:id', noteController.deleteNote);
module.exports = router;
